default:
    resource: "@DefaultBundle/Resources/config/routing.yml"

default_catalog:
    resource: "@DefaultBundle/Resources/config/routing_catalog.yml"

PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /
    
app:
    resource: '@AppBundle/Controller/'
    type: annotation
